# Generated by Django 6.0.6 on 2026-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
